#!/usr/bin/env python

import os
import sys
import imp
import argparse

import pymark.packer

parser = argparse.ArgumentParser(description='Create PyMark binaries')
parser.add_argument('input', metavar='<input.py>', nargs=1, help='Input Python file')

args = parser.parse_args()

module = imp.load_source('__pymark__', args.input[0])
module_object = os.path.splitext(os.path.basename(args.input[0]))[0]

output_object = module.__dict__[module_object]
pymark.packer.pack_file(module_object+".pmk", output_object)
